version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"  
      # - run:
      #     name: Lint
      #     command: npm run ng lint
      - run:
          name: Unit Test
          command: npm run ng test -- --watch=false --code-coverage
      # - run:
      #     name: E2E Test
      #     command: npm run ng e2e
      - run:
          name: Coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run:
          name: Build
          command: npm run ng build -- --prod      